version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: monexa
      POSTGRES_PASSWORD: monexa_pass
      POSTGRES_DB: monexa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@monexa.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
